// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxBsELlAqmcEqLJJjiCKXI5d7BUz8R7-Y',
    appId: '1:9473051446:web:db3bdcc7ff8327c5d48197',
    messagingSenderId: '9473051446',
    projectId: 'style-cv',
    authDomain: 'style-cv.firebaseapp.com',
    storageBucket: 'style-cv.firebasestorage.app',
    measurementId: 'G-26Q3GZ7HC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3uAZfxMtQCyWd24mDxcBCDf5iSbD_RxM',
    appId: '1:9473051446:android:b878c76858356381d48197',
    messagingSenderId: '9473051446',
    projectId: 'style-cv',
    storageBucket: 'style-cv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAroVbI3V5RiJjax9BmGF55H8XUweYjjnc',
    appId: '1:9473051446:ios:eee06e77f7502639d48197',
    messagingSenderId: '9473051446',
    projectId: 'style-cv',
    storageBucket: 'style-cv.firebasestorage.app',
    iosBundleId: 'com.example.stylecv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAroVbI3V5RiJjax9BmGF55H8XUweYjjnc',
    appId: '1:9473051446:ios:eee06e77f7502639d48197',
    messagingSenderId: '9473051446',
    projectId: 'style-cv',
    storageBucket: 'style-cv.firebasestorage.app',
    iosBundleId: 'com.example.stylecv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxBsELlAqmcEqLJJjiCKXI5d7BUz8R7-Y',
    appId: '1:9473051446:web:951e65978b4c41c5d48197',
    messagingSenderId: '9473051446',
    projectId: 'style-cv',
    authDomain: 'style-cv.firebaseapp.com',
    storageBucket: 'style-cv.firebasestorage.app',
    measurementId: 'G-XNDEMHZ2H9',
  );
}
