name: stylecv
description: "A Flutter application for generating professional CVs with multiple styles."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12

  google_sign_in: ^5.4.2
  google_sign_in_web: ^0.10.2+1

  pdf: ^3.10.0
  printing: ^5.9.1
  path_provider: ^2.1.1
  open_file: ^3.3.1

  flutter_signin_button: ^2.0.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  flutter_colorpicker: ^1.0.3
  file_picker: ^10.2.0
  image_picker: ^1.0.4

  webview_flutter: ^4.0.1
  flutter_inappwebview: ^6.0.0-beta.21

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^9.0.0

  provider: ^6.1.1

  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/google.png
